name: Deploy to Coolify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Coolify registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.COOLIFY_REGISTRY_URL }}
          username: ${{ secrets.COOLIFY_REGISTRY_USERNAME }}
          password: ${{ secrets.COOLIFY_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.COOLIFY_REGISTRY_URL }}/evai-matchmaking:latest

# Configurez les secrets dans GitHub :
# COOLIFY_REGISTRY_URL, COOLIFY_REGISTRY_USERNAME, COOLIFY_REGISTRY_PASSWORD
# Coolify doit être configuré pour écouter le registre et déployer automatiquement.
